#!/usr/bin/env ruby
dev_database = "monkey_charger_development"

`mongrel_rails stop`
sleep 1

`dropdb #{dev_database}`
`createdb #{dev_database}`

system "rake db:migrate"

`mongrel_rails start -d -p 3001`

